name: Deploy to GitHub Pages

on:
  push:
    branches: [master]  # or your default branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./react/react-app

      - name: Build project
        run: npm run build
        working-directory: ./react/react-app

      - name: Deploy to GitHub Pages under subfolder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./react/react-app/dist
          destination_dir: react/react-app/dist  # 👈 This puts the build inside this folder in gh-pages branch
