name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./react/react-app

      - name: Build project
        run: npm run build
        working-directory: ./react/react-app

      - name: Move 404.html to root if exists
        run: |
          mkdir -p temp-deploy/react/react-app
          cp -r react/react-app/dist/* temp-deploy/react/react-app/
          if [ -f temp-deploy/react/react-app/404.html ]; then
            cp temp-deploy/react/react-app/404.html temp-deploy/404.html
          fi

      - name: Deploy to GitHub Pages with hard reset
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp-deploy
          destination_dir: .
          force_orphan: true
